### ISSUE TITLE
2.0: Todo Sample bug Fix and implement remaining features

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1217]
Bug Fix:
- [x] `Document.getString() and getObject()` for pull replicated document returns `null`
  - This issue is caused by https://github.com/couchbase/couchbase-lite-core/issues/156
- [x] Share feature does not work with ToDo with DB010 

Remainings:
- [x] Live Query - Lists, Tasks,and Users
- [x] Test Share feature
- [x] Blob push/pull replication
- [ ] Conflict resolver
- [ ] Add logout
- [ ] Add task count for the tasks in the list

**Comment by hideki** [comment]
Fixed some Todo v.2.0 sample issues. Remaining issues will be tracked in https://github.com/couchbaselabs/mobile-training-todo/issues repo.
